### ISSUE TITLE
Setup a webpage in https://kerala.openstreetmap.in/

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/SotM#1]
we need to Setup a webpage in https://kerala.openstreetmap.in/
updates happening at https://wiki.openstreetmap.org/wiki/OSM_Kerala_Community_Meetup_2024

**Comment by joicemjoseph** [comment]
first version deployed. (ref: https://github.com/osmkerala/osmkerala.github.io/commit/3d5d50fdfb7c37572a5847b1161d907b6cd75bb2)

**Comment by manojkmohan** [comment]
Thanks @joicemjoseph 

As per discussion in working group, the current page need to move kerala.stateofthemap.in and remain the URL like a Project List and point towords sotm event page.

**Comment by joicemjoseph** [comment]
please close this issue as this requirement is sorted
