### ISSUE TITLE
kerala.stateofthemap.in need to deploy

### ISSUE THREAD

**Issue by manojkmohan** [osmkerala/SotM#6]
Domain credentials with Arjun. 
Followup of this issue https://github.com/osmkerala/SotM/issues/1

simple page enough with basic information and links. can refer this https://stateofthemap.asia/

**Comment by joicemjoseph** [comment]
it would be helpful if you can mention exact details needed to be shown.

**Comment by manojkmohan** [comment]
@joicemjoseph can you update the logos and other information in wiki to website

**Comment by joicemjoseph** [comment]
this is done
